# Generated by Django 4.0.5 on 2022-06-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('lender', 'Lender'), ('borrower', 'Borrower')], default='borrower', max_length=10),
        ),
    ]
