# Generated by Django 4.0.5 on 2022-07-09 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_message_is_read_user_address_user_adhar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='duration',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='ended_at',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reciever', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='call',
            name='created_at',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caller', to=settings.AUTH_USER_MODEL),
        ),
    ]
