# Generated by Django 4.0.5 on 2022-06-22 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_one', models.CharField(blank=True, max_length=1000, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='media/files/')),
                ('doc_two', models.CharField(blank=True, max_length=1000, null=True)),
                ('file_two', models.FileField(blank=True, null=True, upload_to='media/files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('starred_by', models.ManyToManyField(related_name='starred_by', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
